### ISSUE TITLE
Make Maven behave this way by default?

### ISSUE THREAD

**Issue by coconutpalm** [takari/takari-pom#3]
Hi Jason,

This isn't exactly an issue, but I didn't know how better to ask this question.  If you have a better means for communication in the future, please let me know.

I was wondering how hard it would be to make a custom version of Maven with the settings expressed in your parent POM enabled by default?  e.g.: If someone wanted the legacy compiler plug-in they would have to enable it explicitly and override the Takari one.

Thanks,

Dave Orme

**Comment by mosabua** [comment]
It would require a custom Maven distro and in our experience that doesnt work well at all. That was one of the main reasons behind developing Maven extensions. That might be your best bet .. create a extension that rejigs things and then configure it to be used in the projects as desired. But then you could also just maintain a parent pom for your org like this one and do the same by using the parent.. so ... ymmv
