### ISSUE TITLE
Release version 25

### ISSUE THREAD

**Issue by mosabua** [takari/takari-pom#5]
From my point of view there are enough good changes in terms of plugin upgrades that we should cut another release. I am happy to do that if you are okay with it @ifedorenko and @jvanzyl 

Subsequently I am going to use it for maven wrapper, maven plugin and polyglot maven releases....

**Comment by mosabua** [comment]
Tested on maven-wrapper and takari-maven-plugins. 

Any others I can/should test this with specifically before we cut a release?

**Comment by mosabua** [comment]
Ping @ifedorenko ...

**Comment by mosabua** [comment]
works for building takari/bpm

**Comment by mosabua** [comment]
works for building takari/takari-lifecycle

**Comment by ifedorenko** [comment]
@mosabua just release it. in the worst case we'd need to release new version of 25 proves to have problems for some projects.

**Comment by mosabua** [comment]
also works with takari//concurrent-build-logger

I will proceed with the release. Thanks @ifedorenko

**Comment by mosabua** [comment]
Released from ossrh. Should be in central shortly.

**Comment by mosabua** [comment]
http://repo1.maven.org/maven2/io/takari/takari/25/
