### ISSUE TITLE
Mojohaus license plugin

### ISSUE THREAD

**Issue by mosabua** [takari/takari-pom#8]
We are currently using the unmaintained license maven plugin from mycilia. I think we probably want to move to the better maintained mojohaus one .. unfortunately they are not fully compatible.

We should look into making the transition smooth if somehow possible.

**Comment by cstamas** [comment]
See https://github.com/takari/takari-pom/issues/8
may be related

**Comment by cstamas** [comment]
As spotless can apply license/header as well...

**Comment by cstamas** [comment]
Actually mycila + spotless works just fine

**Comment by cstamas** [comment]
Superseded by https://github.com/takari/takari-pom/issues/19
